Feature/consumer producer interceptors
interfax-group/rabbit-link pull request #3
Opened 2023-02-14 21:00 UTC by Fildrance

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Builders/LinkConsumerBuilder.cs
> +            IReadOnlyList<IDeliveryInterceptor> deliveryInterceptors = null
В параметре лучше использовать IEnumerable<T> для гибкости

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Builders/LinkConsumerBuilder.cs
> +            }
Разные стили форматирования `if`

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Builders/LinkConsumerBuilder.cs
> +        private readonly IReadOnlyList<IDeliveryInterceptor> _deliveryInterceptors;
Почему не `IReadOnlyCollection`?
В ProducerBuilder используется именно `IReadOnlyCollection`

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Consumer/LinkConsumer.cs
>              }
Очень странная реализация. 
Дословно:
```csharp
var invocation = new DeliveryInvocation(_interceptors.LastOrDefault());
task = invocation.Intercept(msg, cancellation, (message, ct) => _configuration.MessageHandler(message));
```
Берётся только последний перехватчик. И даже если его нет, `invokation` создаётся и используется

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Consumer/LinkConsumer.cs
> +        private class DeliveryInvocation
Простейшее описание для других разработчиков

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Extensions/LinkConsumerBuilderExtensions.cs
> +    public static class LinkConsumerBuilderExtensions
Отсутствуют описания

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Extensions/LinkConsumerBuilderExtensions.cs
> +    public static class LinkConsumerBuilderExtensions
Название LinkConsumerBuilderExtensions некорректно - внутри методы не только для построителя подписчика

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Extensions/LinkConsumerBuilderExtensions.cs
> +namespace RabbitLink.Extensions
`file-scoped namespace` для новых файлов?

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Interceptors/GzipMessageInterceptor.cs
> +            var result = new LinkConsumedMessage<byte[]>(newStream.ToArray(), msg.Properties, msg.ReceiveProperties, msg.Cancellation);
После `newStream.Position = 0;` ненужные объекты `byteStream` и `compressor` нужно закрыть/освободить (using с блоком):
```csharp
            using var newStream = new MemoryStream();

            using (var byteStream = new MemoryStream(msg.Body))
            using (var compressor = new GZipStream(byteStream, _level))
            {
                await compressor.CopyToAsync(newStream);
                newStream.Position = 0;
            }

            var result = new LinkConsumedMessage<byte[]>(newStream.ToArray(), msg.Properties, msg.ReceiveProperties, msg.Cancellation);
```

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Interceptors/GzipMessageInterceptor.cs
> +    public interface IMessageInterceptor : IDeliveryInterceptor, IPublishInterceptor
Все public классы в отдельные файлы

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Interceptors/GzipMessageInterceptor.cs
> +    public interface IMessageInterceptor : IDeliveryInterceptor, IPublishInterceptor
Отсутствуют описания классов/интерфейсов/методов

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Producer/LinkProducer.cs
> +                    throw new ObjectDisposedException(GetType().Name);
Я думаю, здесь будет полезен комментарий - "почему так"

2023-02-15 09:11 UTC, df-ivanov commented on src/RabbitLink/Producer/LinkProducer.cs
> -            try
Почему убран `try/catch`?

2023-02-15 15:03 UTC, Fildrance commented on src/RabbitLink/Consumer/LinkConsumer.cs
> +                for (int i = 0; i < _interceptors.Count; i++)
обратный порядок тут должен быть

2023-02-15 15:06 UTC, Fildrance commented on src/RabbitLink/Consumer/LinkConsumer.cs
> +                task = invocation.Intercept(msg, cancellation, (message, ct) => _configuration.MessageHandler(message));
если 0 перехватчиков - не надо создавать invocation???

2023-02-15 15:07 UTC, Fildrance commented on src/RabbitLink/Producer/LinkProducer.cs
> -            try
это try-catch на _messageQueue.Put и обработчик там был для него специфический - потому что из _messageQueue.Put может вывалиться походу только этот Exception

2023-02-15 15:21 UTC, Fildrance commented on src/RabbitLink/Builders/LinkConsumerBuilder.cs
> +        private readonly IReadOnlyList<IDeliveryInterceptor> _deliveryInterceptors;
У IReadOnlyList есть индексер, с ним задачу по обходу перехватчиков проще будет решить. Из-за дизайна билдера просто Queue лепить не вариант, а immutable если делать то это пакеты надо подключать - пуска будет уж IReadOnlyList везде как меньшее из зол.

2023-02-15 15:24 UTC, Fildrance commented on src/RabbitLink/Builders/LinkConsumerBuilder.cs
> +            IReadOnlyList<IDeliveryInterceptor> deliveryInterceptors = null
Так как эта конструкция (и соседний конструктор как следствие) используется при каждом вызове метода builder'а - трансформировать каждый раз из IEnumerable в IReadOnlyList будет как минимум неловко. По гайдлайнам правильнее IEnumerable конечно, но в приватном конструкторе он не принесет пользы.

2023-02-15 15:25 UTC, Fildrance commented on src/RabbitLink/Builders/LinkConsumerBuilder.cs
> +            }
good call, Унифицировал вместе с остальным кодом

2023-02-15 18:20 UTC, Fildrance commented on src/RabbitLink/Consumer/LinkConsumer.cs
> +                for (int i = 0; i < _interceptors.Count; i++)
перенес в конструктор чтобы не пересоздавать

2023-02-15 18:20 UTC, Fildrance commented on src/RabbitLink/Consumer/LinkConsumer.cs
> +                task = invocation.Intercept(msg, cancellation, (message, ct) => _configuration.MessageHandler(message));
поправил

2023-02-15 18:20 UTC, Fildrance commented on src/RabbitLink/Consumer/LinkConsumer.cs
>              }
поправил

2023-02-15 18:26 UTC, Fildrance commented on src/RabbitLink/Extensions/LinkConsumerBuilderExtensions.cs
> +    public static class LinkConsumerBuilderExtensions
Попробовал переименовать.

2023-02-15 18:27 UTC, Fildrance commented on src/RabbitLink/Extensions/LinkConsumerBuilderExtensions.cs
> +namespace RabbitLink.Extensions
fixed

2023-02-15 18:27 UTC, Fildrance commented on src/RabbitLink/Extensions/LinkConsumerBuilderExtensions.cs
> +    public static class LinkConsumerBuilderExtensions
fixed

2023-02-15 18:42 UTC, Fildrance commented on src/RabbitLink/Interceptors/GzipMessageInterceptor.cs
> +    public interface IMessageInterceptor : IDeliveryInterceptor, IPublishInterceptor
fixed

2023-02-15 18:42 UTC, Fildrance commented on src/RabbitLink/Interceptors/GzipMessageInterceptor.cs
> +    public interface IMessageInterceptor : IDeliveryInterceptor, IPublishInterceptor
fixed

2023-02-15 20:50 UTC, Fildrance commented on src/RabbitLink/Producer/LinkProducer.cs
> +                    throw new ObjectDisposedException(GetType().Name);
это try-catch на _messageQueue.Put и обработчик там был для него специфический - потому что из _messageQueue.Put может вывалиться походу только этот Exception, я бы оригинальный код тут не дополнял - судя по дизайну оригинальному это в целом очевидно. Хотя решение в целом делать это через channel я не сказать чтобы поддерживаю ;)

2023-02-15 21:08 UTC, Fildrance commented on src/RabbitLink/Consumer/LinkConsumer.cs
> +        private class DeliveryInvocation
fixed

2023-02-16 07:54 UTC, df-ivanov commented on src/RabbitLink/Builders/LinkConsumerBuilder.cs
> +            IReadOnlyList<IDeliveryInterceptor> deliveryInterceptors = null
Если не подразумевается иного использования, ok

2023-02-16 07:56 UTC, df-ivanov commented on src/RabbitLink/Builders/LinkConsumerBuilder.cs
> +        private readonly IReadOnlyList<IDeliveryInterceptor> _deliveryInterceptors;
Я про другое - в аналогичном случае (producer) используется IReadonlyCollection.
В чём отличие?

2023-03-24 09:37 UTC, df-ivanov commented on src/RabbitLink/Extensions/BuilderExtensions.cs
> +/// Extension methods for <see cref="ILinkConsumerBuilder"/>.
Описание не совсем корректно. Здесь и методы для издателя в том числе

2023-03-24 09:37 UTC, df-ivanov commented on src/RabbitLink/Interceptors/IMessageInterceptor.cs
> +public interface IMessageInterceptor : IDeliveryInterceptor, IPublishInterceptor
Очень специфичный интерфейс. Стоит ли?

2023-04-10 09:34 UTC, df-ivanov requested changes

2023-04-10 09:34 UTC, df-ivanov commented on src/RabbitLink/Interceptors/GzipMessageInterceptor.cs
> +            decompressedBytes = decompressedStream.ToArray();
```csharp
using (var compressor = new GZipStream(sourceStream, CompressionMode.Decompress))
{
    compressor.CopyTo(decompressedStream);
}
```

2023-04-10 09:34 UTC, df-ivanov commented on src/RabbitLink/Interceptors/GzipMessageInterceptor.cs
> +            decompressedBytes = decompressedStream.ToArray();
Аналогично в компрессоре

2023-04-10 09:34 UTC, df-ivanov commented on src/RabbitLink/Interceptors/GzipMessageInterceptor.cs
> +            compressedBytes = resultStream.ToArray();
```csharp
using (var compressor = new GZipStream(resultStream, _level))
{
    incomingStream.CopyTo(compressor);
}

compressedBytes = resultStream.ToArray();
```

2023-04-10 09:52 UTC, df-ivanov approved these changes

2023-04-11 20:54 UTC, ilia-sazonov approved these changes

2023-04-12 06:48 UTC, merged